/*
HUGE CREDITS TO SEBASTIAN LAGUE!!

My ray intersection code is heavily based off of his first video on raytracing:
https://www.youtube.com/watch?v=Qz0KTGYJtUk
*/
#version 450

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

struct RGB {
    int red;
    int green;
    int blue;
};

layout(std430, binding = 0) buffer Input {
    int giSamples;
    int width;
    int height;
    float camX;
    float camY;
    float camZ;
    float camPitch;
    float camYaw;
    float fov;
    float bounceLightRandomness;
    float shadowsRandomness;
};

layout(std430, binding = 1) buffer Output {
    RGB pixels[__PXWIDTH * __PXHEIGHT]; // these get filled in with width and height at compile time
};

struct Ray {
    vec3 pos;
    vec3 dir;
};

struct Triangle {
    vec3 posA;
    vec3 posB;
    vec3 posC;
    vec3 normalA;
    vec3 normalB;
    vec3 normalC;
};

int getIndex(int x, int y) {
    return y * width + x;
}

RGB getPixel(int x, int y) {
    return pixels[getIndex(x, y)];
}

void setPixel(int x, int y, RGB color) {
    pixels[getIndex(x, y)] = color;
}

//InternalTraceResult rayTriangle(Ray ray, Triangle tri)
//{
//    vec3 edgeAB = tri.posB - tri.posA;
//    vec3 edgeAC = tri.posC - tri.posA;
//    vec3 normalVector = cross(edgeAB, edgeAC);
//    vec3 ao = ray.pos - tri.posA;
//    vec3 dao = cross(ao, ray.dir);
//
//    float determinant = -dot(ray.dir, normalVector);
//    float invDet = 1 / determinant;
//
//    float dst = dot(ao, normalVector) * invDet;
//    float u = dot(edgeAC, dao) * invDet;
//    float v = -dot(edgeAB, dao) * invDet;
//    float w = 1 - u - v;
//
//    InternalTraceResult traceRes;
//    traceRes.hit = determinant >= 1E-6 && dst >= 0 && v >= 0 && w >= 0;
//    traceRes.hitPoint = ray.pos + ray.dir * dst;
//    traceRes.normal = normalize(tri.normalA * w + tri.normalB * u + tri.normalC * v);
//    traceRes.dist = dst;
//    return traceRes;
//}

Ray pixelToWorld(float x, float y)
{
    float aspectRatio = width / height;

    float normX = x / float(width);
    float normY = y / float(height);

    float ndcX = 2.0 * normX - 1.0;
    float ndcY = 2.0 * normY - 1.0;


    float fovRad = 3.14159265359 * fov / 180;
    float tanFov = tan(fovRad / 2);

    float _camX = ndcX * aspectRatio * tanFov;
    float _camY = ndcY * tanFov;
    float _camZ = -1;

    vec3 dir = vec3(_camX, _camY, _camZ);
    dir = normalize(dir);

    float yaw = camYaw;
    float pitch = camPitch;

    // --- Apply Pitch (X axis) ---
    float cosPitch = cos(pitch);
    float sinPitch = sin(pitch);

    float y1 = dir.y * cosPitch - dir.z * sinPitch;
    float z1 = dir.y * sinPitch + dir.z * cosPitch;
    float x1 = dir.x;

    // --- Apply Yaw (Y axis) after pitch ---
    float cosYaw = cos(yaw);
    float sinYaw = sin(yaw);

    float x2 = x1 * cosYaw - z1 * sinYaw;
    float z2 = x1 * sinYaw + z1 * cosYaw;

    dir = vec3(x2, y1, z2);
    dir = normalize(dir);

    Ray ray;
    ray.pos = vec3(camX, camY, camZ);
    ray.dir = dir;
    return ray;
}

//------- ACES TONEMAPPING -------//
float acesHelper(float x)
{
	float a = 2.51;
	float b = 0.03;
	float c = 2.43;
	float d = 0.59;
	float e = 0.14;
	return min(1.0, max(0.0, (x * (a * x + b)) / (x * (c * x + d) + e)));
}

RGB tonemapAces(vec3 color)
{
    float r = acesHelper(color.x);
    float g = acesHelper(color.y);
    float b = acesHelper(color.z);

    RGB finalColor;
    finalColor.red = int(clamp(r * 255.0, 0.0, 255.0));
    finalColor.green = int(clamp(g * 255.0, 0.0, 255.0));
    finalColor.blue = int(clamp(b * 255.0, 0.0, 255.0));
    return finalColor;
}

//------- CLAMP TONEMAPPING -------//

RGB tonemapClamp(vec3 color)
{
    RGB finalColor;
    finalColor.red = int(clamp(color.x * 255.0, 0.0, 255.0));
    finalColor.green = int(clamp(color.y * 255.0, 0.0, 255.0));
    finalColor.blue = int(clamp(color.z * 255.0, 0.0, 255.0));
    return finalColor;
}


uvec2 pos = gl_GlobalInvocationID.xy;
void main()
{
    if (pos.x >= 1280 || pos.y >= 720) return;

    Ray ray = pixelToWorld(pos.x, pos.y);
    vec3 dirColor = ray.dir * 0.5 + 0.5; // map [-1,1] to [0,1]
    setPixel(int(pos.x), int(pos.y), tonemapClamp(dirColor));
}